window.PSD2_DATA = {
  "checked_on": "2026-09-15",
  "expected_period": "2026-Q2",
  "latest": [
    {
      "aisp_availability_pct": 99.5523,
      "aisp_error_pct": "",
      "aisp_response_ms": "",
      "availability_pct": "",
      "bank": "Česká spořitelna",
      "bank_id": "csas",
      "latest_period": "2026-Q2",
      "metric_method": "prumer dennich hodnot z verejneho JSON podle AISP/PISP",
      "note": "Portal poskytuje verejne denni hodnoty dostupnosti pro jednotliva PSD2 API.",
      "pisp_availability_pct": 99.2837,
      "pisp_error_pct": "",
      "pisp_response_ms": "",
      "report_url": "https://developers.erstegroup.com/api-health-check/bank.csas/last-quarter",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://developers.erstegroup.com/api-health-check/bank.csas/last-quarter",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 5.956,
      "aisp_response_ms": 879.2395,
      "availability_pct": "",
      "bank": "ČSOB",
      "bank_id": "csob",
      "latest_period": "2026-Q2",
      "metric_method": "prumer dennich XLSX hodnot; chybovost prevedena z podilu na procenta; uptime chybi",
      "note": "Oficialni reportingova stranka je obcas nestabilni; XLSX publikuje odezvu a chybovost, ale ne dostupnost.",
      "pisp_availability_pct": "",
      "pisp_error_pct": 1.3187,
      "pisp_response_ms": 612.5572,
      "report_url": "https://www.csob.cz/documents/10710/21871290/psd2-q2-2026.xlsx",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.csob.cz/csob/otevrene-bankovnictvi-csob/pro-vyvojare/seznam-api/reporting",
      "status": "partial"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0879,
      "aisp_response_ms": 378.5604,
      "availability_pct": 97.1856,
      "bank": "Komerční banka",
      "bank_id": "kb",
      "latest_period": "2026-Q2",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "note": "Dostupnost je vypoctena z denne publikovane doby provozuschopnosti API.",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.081,
      "pisp_response_ms": 408.4945,
      "report_url": "https://www.kb.cz/getmedia/956647de-9725-4cf0-9975-52c1e3462491/kb-psd2-2026-q2-cz.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.kb.cz/cs/dostupnost-sluzeb-internetoveho-a-otevreneho-bankovnictvi-api",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": "",
      "availability_pct": "",
      "bank": "Raiffeisenbank",
      "bank_id": "rb",
      "latest_period": "",
      "metric_method": "",
      "note": "Dokumenty jsou nacitane dynamicky; dodany sesit obsahuje denni podklad za 2024-Q3, ale chybi overitelny verejny report. Hodnota se proto nepublikuje jako potvrzena dostupnost.",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": "",
      "report_url": "",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.rb.cz/informacni-servis/dokumenty-ke-stazeni",
      "status": "missing"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0066,
      "aisp_response_ms": 62.8242,
      "availability_pct": 98.9736,
      "bank": "Air Bank",
      "bank_id": "air",
      "latest_period": "2026-Q2",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "note": "Dostupnost je vypoctena z denne publikovane doby provozuschopnosti API.",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0075,
      "pisp_response_ms": 72.7143,
      "report_url": "https://www.airbank.cz/file-download/statistiky-dostupnosti-2q-2026",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.airbank.cz/aplikace-tretich-stran/",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.1733,
      "aisp_response_ms": 498.7889,
      "availability_pct": "",
      "bank": "MONETA Money Bank",
      "bank_id": "moneta",
      "latest_period": "rolling-90d-to-2026-09-14",
      "metric_method": "prumer dennich hodnot v klouzavem 90dennim okne; uptime chybi",
      "note": "Banka publikuje klouzavych 90 dni odezvy a chybovosti, nikoli dostupnost/uptime.",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0089,
      "pisp_response_ms": 149.6556,
      "report_url": "https://www.moneta.cz/otevrene-bankovnictvi",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.moneta.cz/otevrene-bankovnictvi",
      "status": "partial"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0199,
      "aisp_response_ms": 22.7143,
      "availability_pct": 99.9809,
      "bank": "Fio banka",
      "bank_id": "fio",
      "latest_period": "2026-Q2",
      "metric_method": "soucet PSD2 API provozu / (provoz + vypadek)",
      "note": "Dostupnost je vypoctena z denni doby provozu a vypadku PSD2 API.",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0034,
      "pisp_response_ms": 16.0,
      "report_url": "https://developers.fio.cz/stats/PSD2_2026Q2.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://developers.fio.cz/stats.html",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": "",
      "availability_pct": "",
      "bank": "mBank",
      "bank_id": "mbank",
      "latest_period": "",
      "metric_method": "",
      "note": "CZ portal pri overeni zobrazoval polska data; vysledek je proto veden jako nekonzistentni zdroj.",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": "",
      "report_url": "",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://developer.api.mbank.cz/reports",
      "status": "missing"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.1567,
      "aisp_response_ms": 345.29,
      "availability_pct": 100.0,
      "bank": "UniCredit Bank",
      "bank_id": "unicredit",
      "latest_period": "2026-Q2",
      "metric_method": "prumer mesicnich hodnot CZ Dedicated Interface",
      "note": "Mesicni data pro CZ, Dedicated Interface; tracker sklada posledni uzavrene ctvrtleti.",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.1567,
      "pisp_response_ms": 248.6567,
      "report_url": "https://developer.unicredit.eu/report?view=kpi",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://developer.unicredit.eu/report?view=kpi",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": 1819.5176,
      "availability_pct": 99.956,
      "bank": "Banka CREDITAS",
      "bank_id": "creditas",
      "latest_period": "2026-Q2",
      "metric_method": "aritmeticky prumer dennich uptime hodnot",
      "note": "Prehledova stranka muze blokovat automaticke klienty; PDF maji stabilni a predvidatelnou adresu. Automaticke nacteni selhalo: HTTP 403 Posledni zname metriky byly zachovany z predchoziho behu.",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": 936.4353,
      "report_url": "https://www.creditas.cz/files/statisticke-udaje-o-dostupnosti-a-vykonu-rozhrani-2q-2026.pdf",
      "scope": "main",
      "source_state": "http-403",
      "source_url": "https://www.creditas.cz/povinne-uverejnovane-informace#statisticke-udaje-o-dostupnosti",
      "status": "blocked"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": "",
      "availability_pct": 99.9951,
      "bank": "Trinity Bank",
      "bank_id": "trinity",
      "latest_period": "2026-Q2",
      "metric_method": "aritmeticky prumer dennich uptime hodnot vsech PSD2 sluzeb",
      "note": "Tracker vybira pouze API report, nikoli paralelni report internetoveho bankovnictvi.",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": "",
      "report_url": "https://www.trinitybank.cz/download/3036",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.trinitybank.cz/otevrene-bankovnictvi/",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": "",
      "availability_pct": "",
      "bank": "Partners Banka",
      "bank_id": "partners",
      "latest_period": "",
      "metric_method": "",
      "note": "Na vyvojarskem portalu nebyla dohledana sekce se statistikami dostupnosti.",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": "",
      "report_url": "",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://psd2.partnersbanka.cz/",
      "status": "missing"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": "",
      "availability_pct": "",
      "bank": "Oberbank",
      "bank_id": "oberbank",
      "latest_period": "",
      "metric_method": "",
      "note": "Verejna stranka funguje, ale odkaz Zverejneni statistiky XS2A smeruje na interni/neplatny hostname.",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": "",
      "report_url": "",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.oberbank.cz/xs2a-interface",
      "status": "missing"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0879,
      "aisp_response_ms": 387.1698,
      "availability_pct": 99.7801,
      "bank": "J&T Banka",
      "bank_id": "jt",
      "latest_period": "2026-Q2",
      "metric_method": "prumer dennich uptime; spolecna error response rate prevedena z podilu na procenta",
      "note": "Reporty jsou vlozene v datech webove aplikace; tracker z nich vybere PSD2 PDF.",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0879,
      "pisp_response_ms": 1482.0,
      "report_url": "https://assets-eu-01.kc-usercontent.com:443/23883f12-8a12-01af-3f05-426faedce691/69bbf441-3b3b-4519-998b-10ec11b07591/Q2-2026_psd2_unavailability.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.jtbank.cz/informacni-povinnost",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 100.0,
      "aisp_response_ms": 1833.6,
      "availability_pct": "",
      "bank": "PPF banka",
      "bank_id": "ppf",
      "latest_period": "2026-Q1",
      "metric_method": "prumer odezvy a chybovosti jen ve dnech s volanimi; banka nepublikuje uptime",
      "note": "PDF publikuje odezvu a chybovost, ale ne uptime; k 2026-09-11 byl nejnovější pouze 2026-Q1.",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": "",
      "report_url": "https://www.ppfbanka.cz/cs/document/download/8437",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.ppfbanka.cz/cs/dokumenty/1868-pristupy-tretich-stran",
      "status": "outdated"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": "",
      "availability_pct": "",
      "bank": "Národní rozvojová banka",
      "bank_id": "nrb",
      "latest_period": "",
      "metric_method": "",
      "note": "Doplněný kandidát mimo původní sešit: oficiální PSD2 API stránka existuje, statistiky nebyly nalezeny.",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": "",
      "report_url": "",
      "scope": "audit-candidate",
      "source_state": "ok",
      "source_url": "https://www.nrb.cz/webklient/api-rozhrani-informace-pro-treti-strany/",
      "status": "missing"
    }
  ],
  "timeseries": [
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0015,
      "aisp_response_ms": 65.5978,
      "availability_pct": 98.5145,
      "bank": "Air Bank",
      "bank_id": "air",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "period": "2024-Q3",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0055,
      "pisp_response_ms": 60.6522,
      "report_url": "https://www.airbank.cz/file-download/statistiky-dostupnosti-3q-2024",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.airbank.cz/aplikace-tretich-stran/",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": 19303.3125,
      "availability_pct": 100.0,
      "bank": "Banka CREDITAS",
      "bank_id": "creditas",
      "metric_method": "aritmeticky prumer dennich uptime hodnot",
      "period": "2024-Q3",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": 856.5625,
      "report_url": "https://www.creditas.cz/files/statisticke-udaje-o-dostupnosti-a-vykonu-rozhrani-3q-2024.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.creditas.cz/povinne-uverejnovane-informace#statisticke-udaje-o-dostupnosti",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.1134,
      "aisp_response_ms": 13.3804,
      "availability_pct": 99.7894,
      "bank": "Fio banka",
      "bank_id": "fio",
      "metric_method": "soucet PSD2 API provozu / (provoz + vypadek)",
      "period": "2024-Q3",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.096,
      "pisp_response_ms": 94.4565,
      "report_url": "https://developers.fio.cz/stats/PSD2_2024Q3.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://developers.fio.cz/stats.html",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0989,
      "aisp_response_ms": 459.8279,
      "availability_pct": 99.87,
      "bank": "J&T Banka",
      "bank_id": "jt",
      "metric_method": "prumer dennich uptime; spolecna error response rate prevedena z podilu na procenta",
      "period": "2024-Q3",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0989,
      "pisp_response_ms": 1122.3804,
      "report_url": "https://assets-eu-01.kc-usercontent.com:443/23883f12-8a12-01af-3f05-426faedce691/09e76d44-266a-412f-bf3a-612acaba1e26/Q3-2024_psd2_unavailability.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.jtbank.cz/informacni-povinnost",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.98,
      "aisp_response_ms": 744.9891,
      "availability_pct": 98.8149,
      "bank": "Komerční banka",
      "bank_id": "kb",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "period": "2024-Q3",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.4526,
      "pisp_response_ms": 654.7717,
      "report_url": "https://www.kb.cz/getmedia/a5f6061e-0081-4018-a97f-0f90695022ac/kb-psd2-2024-q3-cz.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.kb.cz/cs/dostupnost-sluzeb-internetoveho-a-otevreneho-bankovnictvi-api",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 9.0,
      "aisp_response_ms": 157.3333,
      "availability_pct": "",
      "bank": "PPF banka",
      "bank_id": "ppf",
      "metric_method": "prumer odezvy a chybovosti jen ve dnech s volanimi; banka nepublikuje uptime",
      "period": "2024-Q3",
      "pisp_availability_pct": "",
      "pisp_error_pct": 33.3333,
      "pisp_response_ms": 737.3333,
      "report_url": "https://www.ppfbanka.cz/cs/document/download/7993",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.ppfbanka.cz/cs/dokumenty/1868-pristupy-tretich-stran",
      "status": "partial"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 6.5652,
      "aisp_response_ms": 491.6423,
      "availability_pct": "",
      "bank": "ČSOB",
      "bank_id": "csob",
      "metric_method": "prumer dennich XLSX hodnot; chybovost prevedena z podilu na procenta; uptime chybi",
      "period": "2024-Q3",
      "pisp_availability_pct": "",
      "pisp_error_pct": 1.0978,
      "pisp_response_ms": 686.274,
      "report_url": "https://www.csob.cz/documents/10710/21871290/psd2-q3-2024.xlsx",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.csob.cz/csob/otevrene-bankovnictvi-csob/pro-vyvojare/seznam-api/reporting",
      "status": "partial"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0003,
      "aisp_response_ms": 78.5217,
      "availability_pct": 99.3493,
      "bank": "Air Bank",
      "bank_id": "air",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "period": "2024-Q4",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0102,
      "pisp_response_ms": 75.8804,
      "report_url": "https://www.airbank.cz/file-download/statistiky-dostupnosti-4q-2024",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.airbank.cz/aplikace-tretich-stran/",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": 6527.8,
      "availability_pct": 100.0,
      "bank": "Banka CREDITAS",
      "bank_id": "creditas",
      "metric_method": "aritmeticky prumer dennich uptime hodnot",
      "period": "2024-Q4",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": 687.7,
      "report_url": "https://www.creditas.cz/files/statisticke-udaje-o-dostupnosti-a-vykonu-rozhrani-4q-2024.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.creditas.cz/povinne-uverejnovane-informace#statisticke-udaje-o-dostupnosti",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0076,
      "aisp_response_ms": 10.8043,
      "availability_pct": 99.9479,
      "bank": "Fio banka",
      "bank_id": "fio",
      "metric_method": "soucet PSD2 API provozu / (provoz + vypadek)",
      "period": "2024-Q4",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0027,
      "pisp_response_ms": 55.9239,
      "report_url": "https://developers.fio.cz/stats/PSD2_2024Q4.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://developers.fio.cz/stats.html",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.7826,
      "aisp_response_ms": 349.6214,
      "availability_pct": 99.137,
      "bank": "J&T Banka",
      "bank_id": "jt",
      "metric_method": "prumer dennich uptime; spolecna error response rate prevedena z podilu na procenta",
      "period": "2024-Q4",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.7826,
      "pisp_response_ms": 1627.3142,
      "report_url": "https://assets-eu-01.kc-usercontent.com:443/23883f12-8a12-01af-3f05-426faedce691/d178be61-bcf8-4ad0-ac2c-c487f1a80ba0/Q4-2024_psd2_unavailability.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.jtbank.cz/informacni-povinnost",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.4832,
      "aisp_response_ms": 591.5694,
      "availability_pct": 99.4195,
      "bank": "Komerční banka",
      "bank_id": "kb",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "period": "2024-Q4",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.2976,
      "pisp_response_ms": 496.7717,
      "report_url": "https://www.kb.cz/getmedia/465ab7eb-62b6-49f7-9009-54978e40ffe7/kb-psd2-2024-q4-cz.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.kb.cz/cs/dostupnost-sluzeb-internetoveho-a-otevreneho-bankovnictvi-api",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 25.0,
      "aisp_response_ms": 222.0,
      "availability_pct": "",
      "bank": "PPF banka",
      "bank_id": "ppf",
      "metric_method": "prumer odezvy a chybovosti jen ve dnech s volanimi; banka nepublikuje uptime",
      "period": "2024-Q4",
      "pisp_availability_pct": "",
      "pisp_error_pct": 33.3333,
      "pisp_response_ms": 737.3333,
      "report_url": "https://www.ppfbanka.cz/cs/document/download/7995",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.ppfbanka.cz/cs/dokumenty/1868-pristupy-tretich-stran",
      "status": "partial"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 4.5109,
      "aisp_response_ms": 556.3546,
      "availability_pct": "",
      "bank": "ČSOB",
      "bank_id": "csob",
      "metric_method": "prumer dennich XLSX hodnot; chybovost prevedena z podilu na procenta; uptime chybi",
      "period": "2024-Q4",
      "pisp_availability_pct": "",
      "pisp_error_pct": 47.4022,
      "pisp_response_ms": 690.9292,
      "report_url": "https://www.csob.cz/documents/10710/21871290/psd2-q4-2024.xlsx",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.csob.cz/csob/otevrene-bankovnictvi-csob/pro-vyvojare/seznam-api/reporting",
      "status": "partial"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0014,
      "aisp_response_ms": 70.4444,
      "availability_pct": 99.2207,
      "bank": "Air Bank",
      "bank_id": "air",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "period": "2025-Q1",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0138,
      "pisp_response_ms": 75.6556,
      "report_url": "https://www.airbank.cz/file-download/statistiky-dostupnosti-1q-2025",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.airbank.cz/aplikace-tretich-stran/",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": 6809.6667,
      "availability_pct": 100.0,
      "bank": "Banka CREDITAS",
      "bank_id": "creditas",
      "metric_method": "aritmeticky prumer dennich uptime hodnot",
      "period": "2025-Q1",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": 703.6667,
      "report_url": "https://www.creditas.cz/files/statisticke-udaje-o-dostupnosti-a-vykonu-rozhrani-1q-2025.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.creditas.cz/povinne-uverejnovane-informace#statisticke-udaje-o-dostupnosti",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0124,
      "aisp_response_ms": 12.2556,
      "availability_pct": 99.9074,
      "bank": "Fio banka",
      "bank_id": "fio",
      "metric_method": "soucet PSD2 API provozu / (provoz + vypadek)",
      "period": "2025-Q1",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0078,
      "pisp_response_ms": 66.6,
      "report_url": "https://developers.fio.cz/stats/PSD2_2025Q1.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://developers.fio.cz/stats.html",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.1461,
      "aisp_response_ms": 247.7389,
      "availability_pct": 99.7403,
      "bank": "J&T Banka",
      "bank_id": "jt",
      "metric_method": "prumer dennich uptime; spolecna error response rate prevedena z podilu na procenta",
      "period": "2025-Q1",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.1461,
      "pisp_response_ms": 761.2384,
      "report_url": "https://assets-eu-01.kc-usercontent.com:443/23883f12-8a12-01af-3f05-426faedce691/4ba78ea4-28e7-4397-aa4b-d60a304bca46/Q1-2025_psd2_unavailability.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.jtbank.cz/informacni-povinnost",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.3257,
      "aisp_response_ms": 424.1111,
      "availability_pct": 98.206,
      "bank": "Komerční banka",
      "bank_id": "kb",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "period": "2025-Q1",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.5378,
      "pisp_response_ms": 377.3556,
      "report_url": "https://www.kb.cz/getmedia/534311f3-7d66-4bcd-abd6-0f04b41e008f/kb-psd2-2025-q1-cz.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.kb.cz/cs/dostupnost-sluzeb-internetoveho-a-otevreneho-bankovnictvi-api",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 5.2889,
      "aisp_response_ms": 556.6469,
      "availability_pct": "",
      "bank": "ČSOB",
      "bank_id": "csob",
      "metric_method": "prumer dennich XLSX hodnot; chybovost prevedena z podilu na procenta; uptime chybi",
      "period": "2025-Q1",
      "pisp_availability_pct": "",
      "pisp_error_pct": 13.8667,
      "pisp_response_ms": 716.8298,
      "report_url": "https://www.csob.cz/documents/10710/21871290/psd2-q1-2025.xlsx",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.csob.cz/csob/otevrene-bankovnictvi-csob/pro-vyvojare/seznam-api/reporting",
      "status": "partial"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0031,
      "aisp_response_ms": 68.4396,
      "availability_pct": 98.4196,
      "bank": "Air Bank",
      "bank_id": "air",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "period": "2025-Q2",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.447,
      "pisp_response_ms": 77.2967,
      "report_url": "https://www.airbank.cz/file-download/statistiky-dostupnosti-2q-2025",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.airbank.cz/aplikace-tretich-stran/",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": 12818.8571,
      "availability_pct": 100.0,
      "bank": "Banka CREDITAS",
      "bank_id": "creditas",
      "metric_method": "aritmeticky prumer dennich uptime hodnot",
      "period": "2025-Q2",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": 749.5714,
      "report_url": "https://www.creditas.cz/files/statisticke-udaje-o-dostupnosti-a-vykonu-rozhrani-2q-2025.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.creditas.cz/povinne-uverejnovane-informace#statisticke-udaje-o-dostupnosti",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0038,
      "aisp_response_ms": 16.3846,
      "availability_pct": 99.9939,
      "bank": "Fio banka",
      "bank_id": "fio",
      "metric_method": "soucet PSD2 API provozu / (provoz + vypadek)",
      "period": "2025-Q2",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0014,
      "pisp_response_ms": 28.9451,
      "report_url": "https://developers.fio.cz/stats/PSD2_2025Q2.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://developers.fio.cz/stats.html",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.3407,
      "aisp_response_ms": 323.674,
      "availability_pct": 99.5907,
      "bank": "J&T Banka",
      "bank_id": "jt",
      "metric_method": "prumer dennich uptime; spolecna error response rate prevedena z podilu na procenta",
      "period": "2025-Q2",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.3407,
      "pisp_response_ms": 1126.0038,
      "report_url": "https://assets-eu-01.kc-usercontent.com:443/23883f12-8a12-01af-3f05-426faedce691/2477ae19-ff5d-4c6e-bfb4-40c6e8b37ebb/Q2-2025_psd2_unavailability.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.jtbank.cz/informacni-povinnost",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.1527,
      "aisp_response_ms": 378.033,
      "availability_pct": 97.1764,
      "bank": "Komerční banka",
      "bank_id": "kb",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "period": "2025-Q2",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.2333,
      "pisp_response_ms": 409.7582,
      "report_url": "https://www.kb.cz/getmedia/b4eb0997-283f-4ccc-a822-ffc11d2e64dd/kb-psd2-2025-q2-cz.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.kb.cz/cs/dostupnost-sluzeb-internetoveho-a-otevreneho-bankovnictvi-api",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 5.044,
      "aisp_response_ms": 538.3573,
      "availability_pct": "",
      "bank": "ČSOB",
      "bank_id": "csob",
      "metric_method": "prumer dennich XLSX hodnot; chybovost prevedena z podilu na procenta; uptime chybi",
      "period": "2025-Q2",
      "pisp_availability_pct": "",
      "pisp_error_pct": 6.2747,
      "pisp_response_ms": 645.0475,
      "report_url": "https://www.csob.cz/documents/10710/21871290/psd2-q2-2025.xlsx",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.csob.cz/csob/otevrene-bankovnictvi-csob/pro-vyvojare/seznam-api/reporting",
      "status": "partial"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0001,
      "aisp_response_ms": 74.587,
      "availability_pct": 99.1538,
      "bank": "Air Bank",
      "bank_id": "air",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "period": "2025-Q3",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.005,
      "pisp_response_ms": 91.2391,
      "report_url": "https://www.airbank.cz/file-download/statistiky-dostupnosti-3q-2025",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.airbank.cz/aplikace-tretich-stran/",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": 3065.3333,
      "availability_pct": 100.0,
      "bank": "Banka CREDITAS",
      "bank_id": "creditas",
      "metric_method": "aritmeticky prumer dennich uptime hodnot",
      "period": "2025-Q3",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": 1095.0833,
      "report_url": "https://www.creditas.cz/files/statisticke-udaje-o-dostupnosti-a-vykonu-rozhrani-3q-2025.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.creditas.cz/povinne-uverejnovane-informace#statisticke-udaje-o-dostupnosti",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0,
      "aisp_response_ms": 31.0,
      "availability_pct": 99.9864,
      "bank": "Fio banka",
      "bank_id": "fio",
      "metric_method": "soucet PSD2 API provozu / (provoz + vypadek)",
      "period": "2025-Q3",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.032,
      "pisp_response_ms": 19.7826,
      "report_url": "https://developers.fio.cz/stats/PSD2_2025Q3.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://developers.fio.cz/stats.html",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.9121,
      "aisp_response_ms": 467.118,
      "availability_pct": 99.2386,
      "bank": "J&T Banka",
      "bank_id": "jt",
      "metric_method": "prumer dennich uptime; spolecna error response rate prevedena z podilu na procenta",
      "period": "2025-Q3",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.9121,
      "pisp_response_ms": 1867.3218,
      "report_url": "https://assets-eu-01.kc-usercontent.com:443/23883f12-8a12-01af-3f05-426faedce691/4d6eab7e-7571-4256-895b-157c45599a47/Q3-2025_psd2_unavailability.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.jtbank.cz/informacni-povinnost",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.1051,
      "aisp_response_ms": 375.913,
      "availability_pct": 97.7189,
      "bank": "Komerční banka",
      "bank_id": "kb",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "period": "2025-Q3",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.1385,
      "pisp_response_ms": 483.5,
      "report_url": "https://www.kb.cz/getmedia/5e46e9ce-f49c-42c2-9e8d-956d1dd5923f/kb-psd2-2025-q3-cz.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.kb.cz/cs/dostupnost-sluzeb-internetoveho-a-otevreneho-bankovnictvi-api",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 4.0109,
      "aisp_response_ms": 570.8325,
      "availability_pct": "",
      "bank": "ČSOB",
      "bank_id": "csob",
      "metric_method": "prumer dennich XLSX hodnot; chybovost prevedena z podilu na procenta; uptime chybi",
      "period": "2025-Q3",
      "pisp_availability_pct": "",
      "pisp_error_pct": 1.0326,
      "pisp_response_ms": 602.2763,
      "report_url": "https://www.csob.cz/documents/10710/21871290/psd2-q3-2025.xlsx",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.csob.cz/csob/otevrene-bankovnictvi-csob/pro-vyvojare/seznam-api/reporting",
      "status": "partial"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0012,
      "aisp_response_ms": 64.4565,
      "availability_pct": 98.9651,
      "bank": "Air Bank",
      "bank_id": "air",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "period": "2025-Q4",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0105,
      "pisp_response_ms": 74.087,
      "report_url": "https://www.airbank.cz/file-download/statistiky-dostupnosti-4q-2025",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.airbank.cz/aplikace-tretich-stran/",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": 4330.6667,
      "availability_pct": 100.0,
      "bank": "Banka CREDITAS",
      "bank_id": "creditas",
      "metric_method": "aritmeticky prumer dennich uptime hodnot",
      "period": "2025-Q4",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": 700.3333,
      "report_url": "https://www.creditas.cz/files/statisticke-udaje-o-dostupnosti-a-vykonu-rozhrani-4q-2025.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.creditas.cz/povinne-uverejnovane-informace#statisticke-udaje-o-dostupnosti",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0528,
      "aisp_response_ms": 34.0326,
      "availability_pct": 99.9268,
      "bank": "Fio banka",
      "bank_id": "fio",
      "metric_method": "soucet PSD2 API provozu / (provoz + vypadek)",
      "period": "2025-Q4",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0324,
      "pisp_response_ms": 23.0652,
      "report_url": "https://developers.fio.cz/stats/PSD2_2025Q4.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://developers.fio.cz/stats.html",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.3804,
      "aisp_response_ms": 326.79,
      "availability_pct": 99.5698,
      "bank": "J&T Banka",
      "bank_id": "jt",
      "metric_method": "prumer dennich uptime; spolecna error response rate prevedena z podilu na procenta",
      "period": "2025-Q4",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.3804,
      "pisp_response_ms": 1211.06,
      "report_url": "https://assets-eu-01.kc-usercontent.com:443/23883f12-8a12-01af-3f05-426faedce691/ff63715c-e048-4b3b-b137-bf57f723b101/q4-2025_psd2_unavailability.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.jtbank.cz/informacni-povinnost",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0445,
      "aisp_response_ms": 287.2258,
      "availability_pct": 98.8625,
      "bank": "Komerční banka",
      "bank_id": "kb",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "period": "2025-Q4",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0726,
      "pisp_response_ms": 392.0326,
      "report_url": "https://www.kb.cz/getmedia/0d831705-999e-43de-9ec9-f5980ae1f75e/kb-psd2-2025-q4-cz.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.kb.cz/cs/dostupnost-sluzeb-internetoveho-a-otevreneho-bankovnictvi-api",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": "",
      "availability_pct": 99.7473,
      "bank": "Trinity Bank",
      "bank_id": "trinity",
      "metric_method": "aritmeticky prumer dennich uptime hodnot vsech PSD2 sluzeb",
      "period": "2025-Q4",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": "",
      "report_url": "https://www.trinitybank.cz/download/2863",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.trinitybank.cz/otevrene-bankovnictvi/",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 4.25,
      "aisp_response_ms": 683.1147,
      "availability_pct": "",
      "bank": "ČSOB",
      "bank_id": "csob",
      "metric_method": "prumer dennich XLSX hodnot; chybovost prevedena z podilu na procenta; uptime chybi",
      "period": "2025-Q4",
      "pisp_availability_pct": "",
      "pisp_error_pct": 1.5543,
      "pisp_response_ms": 612.2577,
      "report_url": "https://www.csob.cz/documents/10710/21871290/psd2-q4-2025.xlsx",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.csob.cz/csob/otevrene-bankovnictvi-csob/pro-vyvojare/seznam-api/reporting",
      "status": "partial"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0,
      "aisp_response_ms": 70.7889,
      "availability_pct": 99.3789,
      "bank": "Air Bank",
      "bank_id": "air",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "period": "2026-Q1",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0039,
      "pisp_response_ms": 71.7889,
      "report_url": "https://www.airbank.cz/file-download/statistiky-dostupnosti-1q-2026",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.airbank.cz/aplikace-tretich-stran/",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": 470.2889,
      "availability_pct": 99.8333,
      "bank": "Banka CREDITAS",
      "bank_id": "creditas",
      "metric_method": "aritmeticky prumer dennich uptime hodnot",
      "period": "2026-Q1",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": 784.8,
      "report_url": "https://www.creditas.cz/files/statisticke-udaje-o-dostupnosti-a-vykonu-rozhrani-1q-2026.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.creditas.cz/povinne-uverejnovane-informace#statisticke-udaje-o-dostupnosti",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0459,
      "aisp_response_ms": 22.2889,
      "availability_pct": 99.9823,
      "bank": "Fio banka",
      "bank_id": "fio",
      "metric_method": "soucet PSD2 API provozu / (provoz + vypadek)",
      "period": "2026-Q1",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0072,
      "pisp_response_ms": 19.0667,
      "report_url": "https://developers.fio.cz/stats/PSD2_2026Q1.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://developers.fio.cz/stats.html",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0709,
      "aisp_response_ms": 396.7333,
      "availability_pct": 97.8958,
      "bank": "Komerční banka",
      "bank_id": "kb",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "period": "2026-Q1",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.1138,
      "pisp_response_ms": 504.6556,
      "report_url": "https://www.kb.cz/getmedia/dcd64cb6-1aa6-4d60-abc2-b8c9aad4ce28/kb-psd2-2026-q1-cz.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.kb.cz/cs/dostupnost-sluzeb-internetoveho-a-otevreneho-bankovnictvi-api",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 100.0,
      "aisp_response_ms": 1833.6,
      "availability_pct": "",
      "bank": "PPF banka",
      "bank_id": "ppf",
      "metric_method": "prumer odezvy a chybovosti jen ve dnech s volanimi; banka nepublikuje uptime",
      "period": "2026-Q1",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": "",
      "report_url": "https://www.ppfbanka.cz/cs/document/download/8437",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.ppfbanka.cz/cs/dokumenty/1868-pristupy-tretich-stran",
      "status": "outdated"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": "",
      "availability_pct": 99.9944,
      "bank": "Trinity Bank",
      "bank_id": "trinity",
      "metric_method": "aritmeticky prumer dennich uptime hodnot vsech PSD2 sluzeb",
      "period": "2026-Q1",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": "",
      "report_url": "https://www.trinitybank.cz/download/3038",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.trinitybank.cz/otevrene-bankovnictvi/",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 4.9333,
      "aisp_response_ms": 746.2501,
      "availability_pct": "",
      "bank": "ČSOB",
      "bank_id": "csob",
      "metric_method": "prumer dennich XLSX hodnot; chybovost prevedena z podilu na procenta; uptime chybi",
      "period": "2026-Q1",
      "pisp_availability_pct": "",
      "pisp_error_pct": 1.7333,
      "pisp_response_ms": 638.7506,
      "report_url": "https://www.csob.cz/documents/10710/21871290/psd2-q1-2026.xlsx",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.csob.cz/csob/otevrene-bankovnictvi-csob/pro-vyvojare/seznam-api/reporting",
      "status": "partial"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0066,
      "aisp_response_ms": 62.8242,
      "availability_pct": 98.9736,
      "bank": "Air Bank",
      "bank_id": "air",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "period": "2026-Q2",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0075,
      "pisp_response_ms": 72.7143,
      "report_url": "https://www.airbank.cz/file-download/statistiky-dostupnosti-2q-2026",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.airbank.cz/aplikace-tretich-stran/",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": 1819.5176,
      "availability_pct": 99.956,
      "bank": "Banka CREDITAS",
      "bank_id": "creditas",
      "metric_method": "aritmeticky prumer dennich uptime hodnot",
      "period": "2026-Q2",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": 936.4353,
      "report_url": "https://www.creditas.cz/files/statisticke-udaje-o-dostupnosti-a-vykonu-rozhrani-2q-2026.pdf",
      "scope": "main",
      "source_state": "ok-direct-pdf",
      "source_url": "https://www.creditas.cz/povinne-uverejnovane-informace#statisticke-udaje-o-dostupnosti",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0199,
      "aisp_response_ms": 22.7143,
      "availability_pct": 99.9809,
      "bank": "Fio banka",
      "bank_id": "fio",
      "metric_method": "soucet PSD2 API provozu / (provoz + vypadek)",
      "period": "2026-Q2",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0034,
      "pisp_response_ms": 16.0,
      "report_url": "https://developers.fio.cz/stats/PSD2_2026Q2.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://developers.fio.cz/stats.html",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0879,
      "aisp_response_ms": 387.1698,
      "availability_pct": 99.7801,
      "bank": "J&T Banka",
      "bank_id": "jt",
      "metric_method": "prumer dennich uptime; spolecna error response rate prevedena z podilu na procenta",
      "period": "2026-Q2",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.0879,
      "pisp_response_ms": 1482.0,
      "report_url": "https://assets-eu-01.kc-usercontent.com:443/23883f12-8a12-01af-3f05-426faedce691/69bbf441-3b3b-4519-998b-10ec11b07591/Q2-2026_psd2_unavailability.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.jtbank.cz/informacni-povinnost",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.0879,
      "aisp_response_ms": 378.5604,
      "availability_pct": 97.1856,
      "bank": "Komerční banka",
      "bank_id": "kb",
      "metric_method": "soucet minut provozu API / kalendarni minuty",
      "period": "2026-Q2",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.081,
      "pisp_response_ms": 408.4945,
      "report_url": "https://www.kb.cz/getmedia/956647de-9725-4cf0-9975-52c1e3462491/kb-psd2-2026-q2-cz.pdf",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.kb.cz/cs/dostupnost-sluzeb-internetoveho-a-otevreneho-bankovnictvi-api",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": "",
      "aisp_response_ms": "",
      "availability_pct": 99.9951,
      "bank": "Trinity Bank",
      "bank_id": "trinity",
      "metric_method": "aritmeticky prumer dennich uptime hodnot vsech PSD2 sluzeb",
      "period": "2026-Q2",
      "pisp_availability_pct": "",
      "pisp_error_pct": "",
      "pisp_response_ms": "",
      "report_url": "https://www.trinitybank.cz/download/3036",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.trinitybank.cz/otevrene-bankovnictvi/",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 0.1567,
      "aisp_response_ms": 345.29,
      "availability_pct": 100.0,
      "bank": "UniCredit Bank",
      "bank_id": "unicredit",
      "metric_method": "prumer mesicnich hodnot CZ Dedicated Interface",
      "period": "2026-Q2",
      "pisp_availability_pct": "",
      "pisp_error_pct": 0.1567,
      "pisp_response_ms": 248.6567,
      "report_url": "https://developer.unicredit.eu/report?view=kpi",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://developer.unicredit.eu/report?view=kpi",
      "status": "ok"
    },
    {
      "aisp_availability_pct": "",
      "aisp_error_pct": 5.956,
      "aisp_response_ms": 879.2395,
      "availability_pct": "",
      "bank": "ČSOB",
      "bank_id": "csob",
      "metric_method": "prumer dennich XLSX hodnot; chybovost prevedena z podilu na procenta; uptime chybi",
      "period": "2026-Q2",
      "pisp_availability_pct": "",
      "pisp_error_pct": 1.3187,
      "pisp_response_ms": 612.5572,
      "report_url": "https://www.csob.cz/documents/10710/21871290/psd2-q2-2026.xlsx",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://www.csob.cz/csob/otevrene-bankovnictvi-csob/pro-vyvojare/seznam-api/reporting",
      "status": "partial"
    },
    {
      "aisp_availability_pct": 99.5523,
      "aisp_error_pct": "",
      "aisp_response_ms": "",
      "availability_pct": "",
      "bank": "Česká spořitelna",
      "bank_id": "csas",
      "metric_method": "prumer dennich hodnot z verejneho JSON podle AISP/PISP",
      "period": "2026-Q2",
      "pisp_availability_pct": 99.2837,
      "pisp_error_pct": "",
      "pisp_response_ms": "",
      "report_url": "https://developers.erstegroup.com/api-health-check/bank.csas/last-quarter",
      "scope": "main",
      "source_state": "ok",
      "source_url": "https://developers.erstegroup.com/api-health-check/bank.csas/last-quarter",
      "status": "ok"
    }
  ]
}
